version: '3'

services:
  next-app:
    build: ./next-app

    # Set envrionment variables based on the .env file
    volumes:
      - ./next-app/app:/app/app
      - ./next-app/public:/app/public
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/root
    restart: always
    ports:
      - 18082:18082
    networks:
      - my_network
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true